# Generated by Django 4.0.3 on 2022-03-09 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='previous_due',
            new_name='due',
        ),
    ]
