# Generated by Django 4.0.3 on 2022-03-09 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basic_module_app', '0001_initial'),
        ('staff_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetailsInit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('barcode', models.CharField(blank=True, max_length=255, null=True)),
                ('sr_visit_return', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_product_purchase_orders', to='basic_module_app.productinit')),
                ('sr_visit_user', models.ForeignKey(limit_choices_to={'sr': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='get_sr_products', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_admin_purchase_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalesReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(limit_choices_to={'customer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='get_customer_sales_returns', to=settings.AUTH_USER_MODEL)),
                ('product_init', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='get_product_sales_return', to='inventory_app.productdetailsinit')),
                ('sr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_user_sales_returns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approve', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(limit_choices_to={'customer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='get_customer_sales_orders', to=settings.AUTH_USER_MODEL)),
                ('product_init', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='get_product_sales_order', to='inventory_app.productdetailsinit')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.UUID('81838ea0-98de-4cee-8bb5-f83c6943affb'))),
                ('flat_discount_percent', models.IntegerField(blank=True, null=True)),
                ('flat_discount_amount', models.IntegerField(blank=True, null=True)),
                ('net_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adjust_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pay_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Running_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_customer_purchase_order_finance', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_supplier_purchase_order_finance', to='staff_app.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warranty_limit', models.CharField(blank=True, max_length=255, null=True)),
                ('rp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_percent', models.PositiveIntegerField(blank=True, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_category_purchase_orders', to='basic_module_app.category')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_color_purchase_orders', to='basic_module_app.color')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_company_purchase_orders', to='basic_module_app.company')),
                ('pin_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_type_purchase_orders', to='basic_module_app.type')),
                ('product_init', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='get_product_purchase_order', to='inventory_app.productdetailsinit')),
                ('purchase_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='get_purchase_group_all', to='inventory_app.purchaseordergroup')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('product_init', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='get_product_company_return', to='inventory_app.productdetailsinit')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_supplier_sales_returns', to='staff_app.supplier')),
            ],
        ),
    ]
