# Generated by Django 4.0.3 on 2022-03-09 05:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseordergroup',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f28c84ef-c3df-402b-9111-7574e970267e')),
        ),
    ]
