# Generated by Django 4.0.3 on 2022-03-09 05:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0003_alter_purchaseordergroup_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseordergroup',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('cdd58b4b-f58a-4019-8205-5a9230233655')),
        ),
    ]
