# Generated by Django 4.0.3 on 2022-03-12 18:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0005_alter_purchaseordergroup_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdetailsinit',
            old_name='user',
            new_name='admin',
        ),
        migrations.AlterField(
            model_name='purchaseordergroup',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('3b6a06c2-abde-47c5-880e-2aafc9899ccd')),
        ),
    ]
