# Generated by Django 4.0.3 on 2022-03-12 18:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0006_rename_user_productdetailsinit_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetailsinit',
            name='barcode',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='purchaseordergroup',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('56bc74fc-c1e0-4f7e-8851-1718ca9d1282')),
        ),
    ]
