# Generated by Django 4.0.3 on 2022-03-20 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory_app', '0007_alter_productdetailsinit_barcode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetailsinit',
            name='sr_visit_return',
        ),
        migrations.RemoveField(
            model_name='productdetailsinit',
            name='sr_visit_user',
        ),
        migrations.AlterField(
            model_name='purchaseordergroup',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('310555fe-d3da-4609-8c71-bfbe6e0b11d6')),
        ),
        migrations.CreateModel(
            name='SRVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_visit_return', models.BooleanField(default=False)),
                ('product_init', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='get_product_sr_visit', to='inventory_app.productdetailsinit')),
                ('sr_visit_user', models.ForeignKey(limit_choices_to={'sr': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='get_sr_products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
