# Generated by Django 4.0.3 on 2022-03-20 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory_app', '0008_remove_productdetailsinit_sr_visit_return_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetailsinit',
            name='sr_visit_return',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productdetailsinit',
            name='sr_visit_user',
            field=models.ForeignKey(limit_choices_to={'sr': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='get_sr_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaseordergroup',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('7e553de9-e57a-494a-9d3a-0239970513c0')),
        ),
        migrations.DeleteModel(
            name='SRVisit',
        ),
    ]
